"""Generate the browser-loadable serial lookup used by index.html.

The scanner runs from file:// (USB-reader mode), where the browser blocks
fetch() of local files. To stay self-contained and offline-capable, the
catalog is bundled as a <script>-loadable JS file (same pattern as the
vendored ZXing library) instead of being read at runtime.

Source  : serial_lookup.csv produced by the cssim-tvc-catalog project
Output  : data/serial_lookup.js  ->  window.SERIAL_LOOKUP keyed by serial

Each entry carries only the fields the scanner displays per box:
provider_model, name (description), image_path, factura_date. tvc_model is
kept for reference/traceability.

Run from the project root:
    uv run python scripts/transform/build_serial_lookup.py
    uv run python scripts/transform/build_serial_lookup.py --source <path-to-csv>
"""

import argparse
import csv
import json
import sys
from pathlib import Path

# Allow direct invocation (uv run python scripts/transform/build_serial_lookup.py)
# in addition to `python -m`; both need the project root on sys.path.
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from scripts.utils.logger import setup_logging
import logging

DEFAULT_SOURCE = Path(
    "/Users/user/DataWork/github-juandedios/cssim-tvc-catalog/enriched/serial_lookup.csv"
)
OUTPUT = Path(__file__).resolve().parents[2] / "data" / "serial_lookup.js"

# Columns carried into the browser. Keyed by serial; only what the UI shows
# plus tvc_model for traceability back to the catalog.
FIELDS = ("provider_model", "name", "image_path", "factura_date", "tvc_model")

logger = logging.getLogger(__name__)


def build(source: Path) -> dict:
    lookup = {}
    with source.open(newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            serial = (row.get("serial") or "").strip()
            if not serial:
                continue
            lookup[serial] = {k: (row.get(k) or "").strip() for k in FIELDS}
    return lookup


def write_js(lookup: dict, source: Path, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(lookup, ensure_ascii=False, indent=0, sort_keys=True)
    header = (
        "// Generated by scripts/transform/build_serial_lookup.py - do not edit by hand.\n"
        f"// Source: {source}\n"
        f"// Records: {len(lookup)}\n"
        "// Keyed by serial (S/N). Rebuild after the source catalog changes.\n"
    )
    output.write_text(f"{header}window.SERIAL_LOOKUP = {payload};\n", encoding="utf-8")


def main() -> None:
    setup_logging(log_file="build_serial_lookup.log")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE,
                        help=f"Source CSV (default: {DEFAULT_SOURCE})")
    parser.add_argument("--output", type=Path, default=OUTPUT,
                        help=f"Output JS file (default: {OUTPUT})")
    args = parser.parse_args()

    if not args.source.exists():
        raise SystemExit(f"Source not found: {args.source}")

    lookup = build(args.source)
    write_js(lookup, args.source, args.output)
    logger.info("Wrote %d serial entries to %s", len(lookup), args.output)


if __name__ == "__main__":
    main()
